# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ProductCatExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductCatExample
  pod 'ImageLoader'
  pod 'ALCameraViewController'
  pod 'KRProgressHUD'

  target 'ProductCatExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductCatExampleUITests' do
    # Pods for testing
  end

end
